
export const GET_CHAT_REQUEST = 'GET_CHAT_REQUEST'
export const GET_CHAT_SUCCESS = 'GET_CHAT_SUCCESS'
export const GET_CHAT_FAIL = 'GET_CHAT_FAIL'

export const GET_CONVERSATIONS_REQUEST = 'GET_CONVERSATIONS_REQUEST'
export const GET_CONVERSATIONS_SUCCESS = 'GET_CONVERSATIONS_SUCCESS'
export const GET_CONVERSATIONS_FAIL = 'GET_CONVERSATIONS_FAIL'

export const SEND_MESSAGE_REQUEST = 'GET_CHAT_REQUEST'
export const SEND_MESSAGE_SUCCESS = 'GET_CHAT_SUCCESS'
export const SEND_MESSAGE_FAIL = 'GET_CHAT_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'